server:
  port: 8082

spring:
  application:
    name: user-service
    bad_request: 400
    conflict: 409
    success: 200
    not_found: 404

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:user_service}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    # Uncomment to use in production
    # jwtExpirationMs: 3600000
    # jwtRefreshExpirationMs: 86400000

    # For test
    jwtExpirationMs: 6000000
    jwtRefreshExpirationMs: 12000000